# Generated by Django 4.1.4 on 2023-02-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True, verbose_name='آدرس ایمیل'),
        ),
    ]
