# Generated by Django 4.1.4 on 2023-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
