# Generated by Django 4.1.4 on 2022-12-14 15:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_navbar_slug_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('obejcts', django.db.models.manager.Manager()),
            ],
        ),
    ]
