# Generated by Django 4.1.4 on 2022-12-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_alter_product_managers_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
