# Generated by Django 4.1.4 on 2022-12-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=30, unique=True, verbose_name='آدرس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=30, unique=True, verbose_name='آدرس محصول'),
        ),
    ]
